---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install core packages
    ansible.builtin.package:
      name:
        - git
        - stow
      state: latest
      update_cache: yes

  - name: Install packages
    ansible.builtin.package:
      name:
        - htop
        - tmux
      state: latest
      update_cache: yes
